public class cDNA {
    public static void main(String[] args) {
        String dna = "AGGCTGTTGGAGTCAACCTGTTATGGAGGAACATGGTAGATCCTATAATTTTTTCTCATGGCCTATATAGTGCATATTATAGATGTCACCCGCCTGAGTACAAGGTTCGCCGATTGCCCCAAGTTTGTTGGTAGTAATAGTACTCGCGATCTGTAAAGTGCGGATCCGACATGAATGCTATTATGTTATAATCCTTTGTTACGAGAATCCCTTTATCGGGCAGCACGGGAGGTATAGCGCTATATTGTGGAGTTCAGACAGCTGTCCTTTGTTTCTCTACTGGCCGGGATAGTAGAAACCTCAGGAAGCTCCAGCGCACGATATTCCTCAAATACTGCTTCAATCGACTGAGCGGGCTTCCCGTGGTTCCGATGCGGTCGCCCCTAGCATCGTGAGGTGTCCGACATGGACGATACCATCTTGGCCTCATCCAGCACGGCACTTCGATCTTAATGGGCTGAATACTCTGAATATGGTGTTTCTAAGCAGTTGCTGCCCTGGAGCAACGATGCCTGATCTATTCCTTCCTGATCAGGTAGCCAGTGATAATGTAGTACCCGCAAGGCAATATGTGGCGTCAATCCCGAGCAGTTAGCGACCTGATTGCTAAGTGGGGGAATATCGACCATCCAAGAGACCAGCGGGAGTGGTGTGGCCAGCCCGGCCAATTCTCGAAGACTAAAAACTGTGTTTCCTCGTCTTGACCAATAGGTGTATGCGATGAGCCCGCGCGAATGATACGCATGCCATGTAATCGGTCCAAGCTGCCGTCTGCTAGCTAACCGGGTCGCTGGAGCGTCGTCTCAAAGTGCCATGTAGAATTTCGGTTGTTTCTGTACTACGTCGGATCAAGACACGGTGGTGGCATGCGCTTGGATTGATATAATGAAAGACTCTCAATGAACGGGGAAGTTTAAGTCGATTCAGAGCCT";

        int aCount = 0;
        int cCount = 0;
        int gCount = 0;
        int tCount = 0;


        for (int i = 0; i < dna.length(); i++) {
            if (dna.charAt(i) == 'A') {
                aCount++;
            } else if (dna.charAt(i) == 'C') {
                cCount++;
            } else if (dna.charAt(i) == 'G') {
                gCount++;
            } else if (dna.charAt(i) == 'T') {
                tCount++;
            }
        }
        
        System.out.printf("%d %d %d %d\n", aCount, cCount, gCount, tCount);
    }
}